

[soc]
core = ["c0", "c0"]
emul = ["drom_emu", "drom_emu"]

[drom_emu]
type      = "dromajo"
bootroom  = "linux_checkpoint_1"
start_roi = false
rabbit    = 1*1024*1024
detail    = 1*1024*1024
time      = 2*1024*1024

[rand_emu]
type = "random"  # Generate random instructions (coverage testing?)

[bp0]
delay             = 1
btb_history_size  = 0
btb_split_il1     = false  # do not cache entries that can be computed by IL1
btb_size          = 32
btb_line_size     = 1
btb_assoc         = 4
btb_repl_policy   = "LRU"

[bp1]
delay             = 2
btb_history_size  = 0
btb_split_il1     = false  # do not cache entries that can be computed by IL1
btb_size          = 8192
btb_line_size     = 1
btb_assoc         = 4
btb_repl_policy   = "LRU"

[c0]
type  = "ooo"  # ooo or inorder or accel
# Branch Predictor[s] parameters
bp_addr_shift = 0      # bits shifted by branch predictor PC
ras_size      = 32
ras_prefetch  = false
bpred         = ["bp0", "bp1"]


# Fetch parameters
fetch_align       = true
trace_align       = false
target_inline_opt = true   # jumps within cacheline do not flush
fetch_one_line    = true   # jumps within cacheline do not flush
max_bb_cycle      = 1
prefetcher        = "pref_opt"

smt = 1 # Number of STM context

# Memory Parameters
st_fwd_delay = 2
ldq_size     = 96
stq_size     = 64
IL1          = "il1_cache"

decode_delay = 4
rename_delay = 2
fetch_width  = 8
ftq_size     = 12
instq_size   = 16

# Exe Parameters
cluster = ["aunit", "bunit", "cunit"]
max_branches      = 30
drain_on_miss     = false

[alu0]
num = 4
lat = 1

[aunit]
win_size   = 16
recyle_at  = "executed"
num_regs   = 64
late_alloc = false
iAALU      = "alu0"
iRALU      = "alu0"


[il1_cache]
type       = "cache"   # or nice
size       = 32*1024
line_size  = 64
delay      = 2         # hit delay
miss_delay = 8
assoc      = 4

[pref_opt]
type       = "stride"
degree     = 10
distance   = 0

# vtage entries
bimodal_size = 1024
bimodal_width = 8
ntables      = 4

